"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 3
final_space = true
console_title_template = "{{ .Shell }} in {{ .Folder }}"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

[[blocks.segments]]
type = "session"
style = "diamond"
foreground = "p:black"
background = "p:yellow"
leading_diamond = ""
template = " {{ if .SSHSession }} {{ end }}{{ .UserName }} "

[blocks.segments.properties]
cache_duration = "none"

[[blocks.segments]]
type = "path"
style = "powerline"
powerline_symbol = ""
foreground = "p:white"
background = "p:orange"
template = "  {{ .Path }} "

[blocks.segments.properties]
style = "agnoster_short"
cache_duration = "none"
max_depth = 2

[[blocks.segments]]
type = "python"
style = "powerline"
powerline_symbol = ""
foreground = "#100e23"
background = "#906cff"
template = "  {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }} "

[blocks.segments.properties]
cache_duration = "none"
display_mode = "context"

[[blocks.segments]]
type = "git"
style = "powerline"
powerline_symbol = ""
foreground = "p:black"
foreground_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}p:black{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:white{{ end }}",
  "{{ if gt .Ahead 0 }}p:white{{ end }}",
]
background = "p:green"
background_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}",
  "{{ if gt .Ahead 0 }}#49416D{{ end }}",
  "{{ if gt .Behind 0 }}#7A306C{{ end }}",
]
template = " {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} "

[blocks.segments.properties]
branch_max_length = 25
cache_duration = "none"
fetch_status = true
fetch_upstream_icon = true
commit_icon = " "

[[blocks.segments]]
type = "root"
style = "powerline"
powerline_symbol = ""
foreground = "p:white"
background = "p:yellow"
template = "  "

[blocks.segments.properties]
cache_duration = "none"

[[blocks.segments]]
type = "status"
style = "diamond"
foreground = "p:white"
background = "p:blue"
background_templates = ["{{ if gt .Code 0 }}p:red{{ end }}"]
trailing_diamond = ""
template = " {{ if gt .Code 0 }}{{ else }}{{ end }} "

[blocks.segments.properties]
always_enabled = true
cache_duration = "none"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

[[blocks.segments]]
type = "executiontime"
style = "diamond"
foreground = "#AEA4BF"
background = "#29315A"
leading_diamond = ""
trailing_diamond = " "
template = "{{ .FormattedMs }}"

[blocks.segments.properties]
cache_duration = "none"
style = "austin"
threshold = 150

[[blocks.segments]]
type = "text"
style = "diamond"
foreground = "#7FD5EA"
background = "#29315A"
leading_diamond = ""
trailing_diamond = ""
template = "❯"

[blocks.segments.properties]
cache_duration = "none"

[[tooltips]]
type = "aws"
tips = ["aws"]
style = "diamond"
foreground = "p:white"
background = "p:orange"
leading_diamond = ""
trailing_diamond = ""
template = "  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} "

[tooltips.properties]
display_default = true

[[tooltips]]
type = "az"
tips = ["az"]
style = "diamond"
foreground = "p:white"
background = "p:blue"
leading_diamond = ""
trailing_diamond = ""
template = "  {{ .Name }} "

[tooltips.properties]
display_default = true

[transient_prompt]
foreground = "p:black"
background = "transparent"
template = "<p:orange,transparent></><,p:orange> {{ .Folder }} </><p:orange,transparent></> "

[secondary_prompt]
foreground = "p:black"
background = "transparent"
template = "<p:yellow,transparent></><,p:yellow> > </><p:yellow,transparent></> "

[palette]
black = "#262B44"
blue = "#4B95E9"
green = "#59C9A5"
orange = "#F07623"
red = "#D81E5B"
white = "#E0DEF4"
yellow = "#F3AE35"
