[user]
name = "Vincent Ging Ho Yim"
email = "cenviity@gmail.com"

[ui]
default-command = "log"
# diff.format = "git"
diff-editor = ":builtin"
merge-editor = "vscode"
# pager = "delta"
pager = ["less", "-FRX"]

[hints]
resolving-conflicts = false

[colors]
# Highlight hunks with background
"diff removed token" = { bg = "#221111", underline = false }
"diff added token" = { bg = "#002200", underline = false }

[aliases]
ci = ["commit"]
nc = ["next", "--conflict"]
pc = ["prev", "--conflict"]
rb = ["rebase"]
sq = ["squash"]

[template-aliases]
# "format_short_signature(signature)" = "signature.username()"

[gg.ui]
theme-override = "dark"
