[experimental]

[save]
autosave_delay = 1000
format_on_save = true
autosave = "after_delay"

[ai]
rules = ""

[package_management]
manager = "uv"

[keymap]
preset = "default"

[keymap.overrides]

[runtime]
std_stream_max_bytes = 1000000
output_max_bytes = 8000000
auto_reload = "off"
default_sql_output = "auto"
watcher_on_save = "lazy"
reactive_tests = true
auto_instantiate = true
on_cell_change = "autorun"

[server]
follow_symlink = false
browser = "default"

[display]
code_editor_font_size = 14
theme = "dark"
default_table_page_size = 10
default_width = "medium"
dataframes = "rich"
cell_output = "above"

[completion]
activate_on_typing = true
copilot = false

[formatting]
line_length = 79

[language_servers.pylsp]
enable_ruff = true
enable_pydocstyle = false
enable_mypy = true
enable_pylint = false
enable_pyflakes = false
enable_flake8 = false
enabled = true

[diagnostics]

[snippets]
include_default_snippets = true
custom_paths = []
